### ISSUE TITLE
UML syntax: DataType

### ISSUE THREAD

**Issue by ronaldtse** [lutaml/lutaml-uml#10]
<img width="689" alt="Screen Shot 2020-08-03 at 9 25 49 PM" src="https://user-images.githubusercontent.com/11865/89187459-e8dd8680-d5cf-11ea-9860-bc61b88112bb.png">
<img width="677" alt="Screen Shot 2020-08-03 at 9 25 59 PM" src="https://user-images.githubusercontent.com/11865/89187472-eda23a80-d5cf-11ea-818e-e746d3b0a993.png">

e.g.
```
data_type "Banking Information" {
  "art code"
  "CCT Number"
}

primitive Integer

enum Address {
  Mr.
  Mrs.
}
```

Thoughts?

Originally from: https://www.slideshare.net/iscrquinter/uml-omg-fundamental-certification-2

**Comment by w00lf** [comment]
@ronaldtse lets also add `attribute` name to syntax, like this:

```
data_type "Banking Information" {
  attribute "art code"
  attribute "CCT Number"
}

primitive Integer

enum Address {
  attribute "Mr."
  attribute "Mrs."
}
```

**Comment by ronaldtse** [comment]
I think we can add "attribute" for easier parsing for data type, but let's allow a shorthand notation.

For enum, those are not "attributes" but data instances. Calling them `attribute`s is misleading. We can use `entry` or something like that. But still I prefer having a shorthand notation.

**Comment by w00lf** [comment]
> I think we can add "attribute" for easier parsing for data type, but let's allow a shorthand notation.
> 
> For enum, those are not "attributes" but data instances. Calling them `attribute`s is misleading. We can use `entry` or something like that. But still I prefer having a shorthand notation.

Ok, got you, lets introduce short notation: when entry for `enum` or `class` does not equal to predefined names(generalizes| aggregation|method) will treat as a `field` for class or `entry` for enum?

**Comment by ronaldtse** [comment]
Yeah, e.g.:

```
class A {
  my_attr1
  attribute my_attr2
}

enum A {
  my_val1
  entry my_val2
}
```
?

**Comment by w00lf** [comment]
Done in #49
