### ISSUE TITLE
UML syntax: Typed elements

### ISSUE THREAD

**Issue by ronaldtse** [lutaml/lutaml-uml#14]
Typed elements
* A typed element is a named element that can have a type.
  * Ex.- Attributes and parameteres.
* A type specifies a set of values for a typed element.
  * Ex.- Simple data types and classes are types.

<img width="890" alt="Screen Shot 2020-08-03 at 9 54 40 PM" src="https://user-images.githubusercontent.com/11865/89190362-ef6dfd00-d5d3-11ea-85d5-09fe503361da.png">

Proposal:
```
class Booking {
  +booker: customer
}

# class MyClass {
#   +TypedElement: Type
# }
```

**Comment by w00lf** [comment]
@ronaldtse looks good, but i would also add `attribute` notation:
```
class Booking {
  + attribute booker: customer
}
```

**Comment by ronaldtse** [comment]
As per #10 I think we need to allow a shorthand. The keyword "attribute" is fine, but allowing a shorthand of omitting it would be good.

**Comment by w00lf** [comment]
> As per #10 I think we need to allow a shorthand. The keyword "attribute" is fine, but allowing a shorthand of omitting it would be good.

Also, can you lease explain the difference between `typed element` and `derived attribute`?

**Comment by ronaldtse** [comment]
"Typed element" is an attribute that accepts only a certain "Type".
<img width="437" alt="Screen Shot 2020-08-06 at 5 39 20 PM" src="https://user-images.githubusercontent.com/11865/89517042-c33cc100-d80b-11ea-8b4e-b69d9adc87ab.png">

Derived attribute is an attribute that has a value produced/assigned from another place:
https://www.uml-diagrams.org/derived-property.html
<img width="215" alt="Screen Shot 2020-08-06 at 5 41 14 PM" src="https://user-images.githubusercontent.com/11865/89517251-07c85c80-d80c-11ea-85d4-da4533f2c45d.png">

They are prefixed with slash `/myattribute`. The following example is clear.

<img width="465" alt="Screen Shot 2020-08-06 at 5 41 46 PM" src="https://user-images.githubusercontent.com/11865/89517310-1b73c300-d80c-11ea-92f2-ed67ecb2bd05.png">

**Comment by w00lf** [comment]
Implemented in repo
