### ISSUE TITLE
UML syntax: Classes

### ISSUE THREAD

**Issue by ronaldtse** [lutaml/lutaml-uml#28]
Classes
* Def.- A class describes a set of instances that have some features, constraints and semantics. A class is a special classifier.

Notation and Semantics
* Classes are represented by rectangles that carry just the name of the class or the class name plus attributes and operations.
* These three compartments (class name, attributes and operations) are separated by a horizontal line.
* This notation stems from the classifier superclass.

<img width="930" alt="Screen Shot 2020-08-05 at 2 19 11 AM" src="https://user-images.githubusercontent.com/11865/89329893-0db22680-d6c2-11ea-9a98-3326d6b38408.png">

Notation & Semantics
* Instances are never created from an abstract class. An abstract class is intentionally incomplete, thus forming the basis for other subclasses that can have instances.
* An abstract class is represented like a regular class, but the name of the class is set in italics. Optionally, we can add the property string {abstract} below the class name.

**Comment by ronaldtse** [comment]
@w00lf can w close this now?

**Comment by w00lf** [comment]
> @w00lf can w close this now?

Currenty there is no support for `abstract` and `interface` keywords, so I guess its early to close this one

**Comment by ronaldtse** [comment]
Closing this and tracking abstract using a new issue. Thanks!
