### ISSUE TITLE
Supporting GraphViz layout engine

### ISSUE THREAD

**Issue by ronaldtse** [lutaml/lutaml-uml#38]
Since we now have the GraphViz engine, we could support OGDF once the Ruby binding is ready.

This means we can create a concept of "layout engine" so that we can use different adapters for drawing diagrams.

**Comment by ronaldtse** [comment]
This depends on completion of https://github.com/lutaml/ogdf-test/issues/1 .

**Comment by w00lf** [comment]
> For GraphViz we should use a Ruby library:
> 
> * https://github.com/ioquatix/graphviz
> * https://github.com/glejeune/Ruby-Graphviz
> 
> @w00lf will decide which is more suitable to use.

I have inspected both repos and choose Ruby-Graphviz, its better maintained, has better docs. I have created enhancement issue #47 to get read of messy code in formatter/graphviz

**Comment by ronaldtse** [comment]
Thanks @w00lf !
