### ISSUE TITLE
XMI Parser: to parse XMI files into data model

### ISSUE THREAD

**Issue by ronaldtse** [lutaml/lutaml-uml#40]
OMG has a number of XMIs that we should be able to read:
* http://omg.org/spec/UML/20161101/PrimitiveTypes.xmi
* http://omg.org/spec/UML/20161101/UML.xmi

LutaML should be able to read these.

**Comment by w00lf** [comment]
This one was imlemented in lutaml/lutaml-xmi gem, @ronaldtse can we close this one?

**Comment by ronaldtse** [comment]
Definitely. Thanks!
