### ISSUE TITLE
Change graphviz formatter to use Ruby-Graphviz dsl.

### ISSUE THREAD

**Issue by w00lf** [lutaml/lutaml-uml#47]
https://github.com/glejeune/Ruby-Graphviz support rich dsl for creating dot files:

```ruby
require 'ruby-graphviz'

# Create a new graph
g = GraphViz.new( :G, :type => :digraph )

# Create two nodes
hello = g.add_nodes( "Hello" )
world = g.add_nodes( "World" )

# Create an edge between the two nodes
g.add_edges( hello, world )

# Generate output image
g.output( :png => "hello_world.png" )
```

And currently, this gem uses strings notations in order to create diagram elements. They should be changed for  Ruby-Graphviz dsl instead.

**Comment by ronaldtse** [comment]
We should wrap the GraphViz gem with a `class Lutaml::Layout::GraphVizEngine <Engine`, so that we can build a common interface for the future usage of other layout tools.

**Comment by w00lf** [comment]
> We should wrap the GraphViz gem with a `class Lutaml::Layout::GraphVizEngine <Engine`, so that we can build a common interface for the future usage of other layout tools.

Ok, got you, will do

**Comment by w00lf** [comment]
> We should wrap the GraphViz gem with a `class Lutaml::Layout::GraphVizEngine <Engine`, so that we can build a common interface for the future usage of other layout tools.

Done in #48

**Comment by ronaldtse** [comment]
Closing. Thanks @w00lf !
