### ISSUE TITLE
Add support for ISO EXPRESS data models

### ISSUE THREAD

**Issue by w00lf** [lutaml/lutaml-uml#52]

**Comment by ronaldtse** [comment]
@w00lf the support for EXPRESS models should be done in LutaML or lutaml-express (which links to expressir)?

**Comment by w00lf** [comment]
> @w00lf the support for EXPRESS models should be done in LutaML or lutaml-express (which links to expressir)?

As I understand, if we want to use lutaml-uml objects(document/class/enum etc) we need to implement support here, is it not?

**Comment by ronaldtse** [comment]
UML objects are class, enum, etc. but EXPRESS objects are schema, entity, etc. They are different, and therefore the LutaML adapter that links to them have to be different.

**Comment by w00lf** [comment]
> UML objects are class, enum, etc. but EXPRESS objects are schema, entity, etc. They are different, and therefore the LutaML adapter that links to them have to be different.

Can you describe the requirements for lutaml-express? Also, as we need to implement lutaml macro in metanorma, it need to use lutaml repo for parsing, what are the requirements for it?
