### ISSUE TITLE
Please remove activesupport dependency

### ISSUE THREAD

**Issue by opoudjis** [lutaml/lutaml-uml#57]
as with expressir, the dependency of activesupport on tzinfo 1.1 is breaking metanorma-standoc, which depends on tzinfo 2.0. Activesupport 6.1 will support tzinfo 2.0, but is still on rc1.

**Comment by w00lf** [comment]
@opoudjis is this one is still relevant? I have not found this dependency in any of lutaml* gems

**Comment by opoudjis** [comment]
Not relevant, because you or Alexei have eliminated the dependency on activesupport in the stack: it is indeed not there any more. Closing.
