### ISSUE TITLE
Display user-friendly error on failed syntax parsing

### ISSUE THREAD

**Issue by w00lf** [lutaml/lutaml-uml#64]
#63

**Comment by ronaldtse** [comment]
https://github.com/lutaml/lutaml-uml/issues/63#issuecomment-762090791

From @w00lf 
> The error was because of a redundant `<<enumeration>>` keyword on enum type entity:
> 
> ```
> enum <<enumeration>> {
> ....
> ```

**Comment by w00lf** [comment]
Duplicate of https://github.com/lutaml/lutaml-uml/issues/71, fixed in https://github.com/lutaml/lutaml-uml/pull/89
