### ISSUE TITLE
Spec examples from concept-models?

### ISSUE THREAD

**Issue by ronaldtse** [lutaml/lutaml-uml#7]
I noticed that #3 includes models from csd-address repo and have two questions:

1. Can we have concept-models also as examples?
2. Can we translate concept-models and the address profile YAML into the new LutaML UML syntax (which is based on ucd)?

**Comment by w00lf** [comment]
> I noticed that #3 includes models from csd-address repo and have two questions:
> 
> 1. Can we have concept-models also as examples?

Totally, will add them next.

> 2. Can we translate concept-models and the address profile YAML into the new LutaML UML syntax (which is based on ucd)?

I should duplicate yaml examples with LutaML syntax?

**Comment by w00lf** [comment]
Added example from `concept-model` to specs, moved datamodel yaml files to LutaML, glossarist/concept-model#15
