### ISSUE TITLE
lutaml-wsd2uml should not insert <CR> characters

### ISSUE THREAD

**Issue by ronaldtse** [lutaml/lutaml-uml#70]
See screenshot:
<img width="505" alt="Screenshot 2021-03-10 at 10 20 33 PM" src="https://user-images.githubusercontent.com/11865/110643302-ec349280-81ee-11eb-986f-dfe9326950fe.png">

**Comment by w00lf** [comment]
@ronaldtse added carriage symbol filter out in https://github.com/lutaml/lutaml-uml/pull/88
