### ISSUE TITLE
(URGENT) Arrowheads for direct association and generalization association should be different

### ISSUE THREAD

**Issue by ronaldtse** [lutaml/lutaml-uml#73]
Direct associations use a black-filled arrowhead while generalization associations use a non-filled arrowhead.

This is an important bug to fix.

e.g.

![image](https://user-images.githubusercontent.com/11865/110711598-c7fea300-823a-11eb-9829-807aee395a5d.png)

**Comment by w00lf** [comment]
> Direct associations use a black-filled arrowhead while generalization associations use a non-filled arrowhead.
> 
> This is an important bug to fix.
> 
> e.g.
> 
> ![image](https://user-images.githubusercontent.com/11865/110711598-c7fea300-823a-11eb-9829-807aee395a5d.png)

@ronaldtse can you please provide the source of the file you mention above(lutaml)?

**Comment by opoudjis** [comment]
That file is https://github.com/metanorma/metanorma-model-bipm/blob/master/models/BipmStandardDocument.wsd , but it's raw PlantUML. For an example of a file failing, see https://github.com/metanorma/metanorma-model-bsi/blob/main/images/BsiStandardDocument.png , generated from https://github.com/metanorma/metanorma-model-bsi/blob/main/views/BsiStandardDocument.lutaml

**Comment by w00lf** [comment]
@ronaldtse @opoudjis fixed in https://github.com/lutaml/lutaml/pull/25, released new lutaml version: 0.7.2

**Comment by opoudjis** [comment]
Confirmed
