### ISSUE TITLE
Empty `enum` raises generic error

### ISSUE THREAD

**Issue by ronaldtse** [lutaml/lutaml-uml#75]
This generic error is displayed when there is an empty enum

```
enum SomeEnum {
}
```

=>

```
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parslet-1.7.1/lib/parslet/cause.rb:70:in `raise': Failed to match sequence (WHITESPACE? DIAGRAM_DEFINITION) at line 1 char 1. (Parslet::ParseFailed)
```

**Comment by w00lf** [comment]
> This generic error is displayed when there is an empty enum
> 
> ```
> enum SomeEnum {
> }
> ```
> 
> =>
> 
> ```
> /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parslet-1.7.1/lib/parslet/cause.rb:70:in `raise': Failed to match sequence (WHITESPACE? DIAGRAM_DEFINITION) at line 1 char 1. (Parslet::ParseFailed)
> ```

@ronaldtse cant reproduce this one, tested with this file:
```
diagram MyView {
  class ImageMapAreaType {
  }
  enum SomeEnum { 
  }
  data_type SomeEnum {
  }
}
```

**Comment by w00lf** [comment]
@ronaldtse is this one still relevant?

**Comment by ronaldtse** [comment]
Thanks!
