### ISSUE TITLE
Cardinality is not rendered correctly for png and dot

### ISSUE THREAD

**Issue by wkwong-ribose** [lutaml/lutaml-uml#84]
![a](https://user-images.githubusercontent.com/80878223/115661322-dc70a800-a36f-11eb-90a6-3bdbfcaff4d4.png)

**Comment by opoudjis** [comment]
Affects all metanorma model documents

**Comment by w00lf** [comment]
@ronaldtse @wkwong-ribose fixed in 0.7.3

**Comment by w00lf** [comment]
@ronaldtse @opoudjis can we close this one?

**Comment by ronaldtse** [comment]
@wkwong-ribose can you confirm? Thanks.

**Comment by wkwong-ribose** [comment]
> Here is the original file copied from the LutaML website.
> 
> diagram MyView {
> title 'My diagram'
> class Customer {
> name: String[0..*]
> -phone: String
> }
> class Order {
> deliveryLocation: Location
> number: Integer[0..1]
> }
> class Location {
> city
> address
> }
> class NormalOrder {
> deliveryLocation: Location
> number: Integer[0..1]
> }
> class FastDeliveryOrder {
> deliveryLocation: Location
> number: Integer[0..1]
> }
> association {
> owner NormalOrder
> member Order
> }
> association {
> owner FastDeliveryOrder
> member Order
> }
> association {
> member_type direct
> owner Order
> member Customer
> }
> association {
> member_type aggregation
> owner Location
> member Order
> }
> }

Using the input here, it does not generate anything (0 byte output).
I recall that there is some change on the syntax.
Is it related?
I am using the lutaml program in the exe folder directly

**Comment by w00lf** [comment]
> > Here is the original file copied from the LutaML website.
> > diagram MyView {
> > title 'My diagram'
> > class Customer {
> > name: String[0..*]
> > -phone: String
> > }
> > class Order {
> > deliveryLocation: Location
> > number: Integer[0..1]
> > }
> > class Location {
> > city
> > address
> > }
> > class NormalOrder {
> > deliveryLocation: Location
> > number: Integer[0..1]
> > }
> > class FastDeliveryOrder {
> > deliveryLocation: Location
> > number: Integer[0..1]
> > }
> > association {
> > owner NormalOrder
> > member Order
> > }
> > association {
> > owner FastDeliveryOrder
> > member Order
> > }
> > association {
> > member_type direct
> > owner Order
> > member Customer
> > }
> > association {
> > member_type aggregation
> > owner Location
> > member Order
> > }
> > }
> 
> Using the input here, it does not generate anything (0 byte output).
> I recall that there is some change on the syntax.
> Is it related?
> I am using the lutaml program in the exe folder directly

hi there, @wkwong-ribose , what version of dot are you using? I tried to compile it myself and also got an error, upgrade from 2.47.2 -> 2.47.3 solved the issue and its worked. Here is an issue on graphviz forum: https://forum.graphviz.org/t/assert-sz-2-in-convertsptoroute/689/2

**Comment by wkwong-ribose** [comment]
Thanks @w00lf. Upgrading to 2.47.3 solved the problem.
